name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install and build packages
        run: |
          make install
          make build

      - name: Run linter
        run: make lint