name: main
on: push
jobs:
  build:
    name: Run lint scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install packages
        run: make install
      - name: linter
        run: make lint